title: Kia Ghods' Personal Portfolio
email: kia.ghods@princeton.edu
description: >- # this means to ignore newlines until "baseurl:"
  Hi I'm Kia -- math + cs @ princeton. Welcome to my personal portfolio!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kiaghods.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ""
github_username:  kiaghods
linkedin_username: kia-ghods
googlescholar_username: maFTcpkAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
